### ISSUE TITLE
`-1` at size_t is a postivie number (equal to SIZE_MAX)

### ISSUE THREAD

**Issue by JarvisCraft** [bmstu-iu8-mentors-cpp-2019/02-lab-01-string-JarvisCraft#1]
https://github.com/bmstu-iu8-mentors-cpp-2019/02-lab-01-string-JarvisCraft/blob/e491719f8522392533e9218768818568a2a2edb1/include/string.hpp#L54
Function requires `-1` as its return value whenever there is no value found. Yet, as its type is `unsigned`, this becomes a maximal positive number (which may, in theory, correspond to an actual position).

As a possible workaround, `std::optional<size_t>` may be used instead.

**Comment by Frumka** [comment]
Адекватное замечание, а нормальных языках так и поступили бы. Но так как лаба основана на std::string мы создаём эквивалентные стандарту функции. А стандартный std::string::find возвращает константу std::string::npos в случае, если подстрока не найдена. А эта константа в точности равна максимально возможному значению переменной size_t.

Смысл такой реализации в максимальной экономии ресурсов исходящей из допущения, что никому не нужна строка в ~18446744073709551615 символов.
